/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTranscripcionRouteImport } from './routes/_authenticated/transcripcion'
import { Route as AuthenticatedResultadosRouteImport } from './routes/_authenticated/resultados'
import { Route as AuthenticatedMesasRouteImport } from './routes/_authenticated/mesas'
import { Route as AuthenticatedEstadoMesasRouteImport } from './routes/_authenticated/estado-mesas'
import { Route as AuthenticatedDelegadosRouteImport } from './routes/_authenticated/delegados'
import { Route as AuthenticatedControlCalidadRouteImport } from './routes/_authenticated/control-calidad'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedCambiarPasswordTemporalRouteImport } from './routes/_authenticated/cambiar-password-temporal'
import { Route as AuthenticatedAsignacionesRouteImport } from './routes/_authenticated/asignaciones'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTranscripcionRoute =
  AuthenticatedTranscripcionRouteImport.update({
    id: '/transcripcion',
    path: '/transcripcion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultadosRoute = AuthenticatedResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesasRoute = AuthenticatedMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstadoMesasRoute =
  AuthenticatedEstadoMesasRouteImport.update({
    id: '/estado-mesas',
    path: '/estado-mesas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDelegadosRoute = AuthenticatedDelegadosRouteImport.update({
  id: '/delegados',
  path: '/delegados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedControlCalidadRoute =
  AuthenticatedControlCalidadRouteImport.update({
    id: '/control-calidad',
    path: '/control-calidad',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCambiarPasswordTemporalRoute =
  AuthenticatedCambiarPasswordTemporalRouteImport.update({
    id: '/cambiar-password-temporal',
    path: '/cambiar-password-temporal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAsignacionesRoute =
  AuthenticatedAsignacionesRouteImport.update({
    id: '/asignaciones',
    path: '/asignaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/asignaciones': typeof AuthenticatedAsignacionesRoute
  '/cambiar-password-temporal': typeof AuthenticatedCambiarPasswordTemporalRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/control-calidad': typeof AuthenticatedControlCalidadRoute
  '/delegados': typeof AuthenticatedDelegadosRoute
  '/estado-mesas': typeof AuthenticatedEstadoMesasRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/transcripcion': typeof AuthenticatedTranscripcionRoute
  '/users': typeof AuthenticatedUsersRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/asignaciones': typeof AuthenticatedAsignacionesRoute
  '/cambiar-password-temporal': typeof AuthenticatedCambiarPasswordTemporalRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/control-calidad': typeof AuthenticatedControlCalidadRoute
  '/delegados': typeof AuthenticatedDelegadosRoute
  '/estado-mesas': typeof AuthenticatedEstadoMesasRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/transcripcion': typeof AuthenticatedTranscripcionRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/asignaciones': typeof AuthenticatedAsignacionesRoute
  '/_authenticated/cambiar-password-temporal': typeof AuthenticatedCambiarPasswordTemporalRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/control-calidad': typeof AuthenticatedControlCalidadRoute
  '/_authenticated/delegados': typeof AuthenticatedDelegadosRoute
  '/_authenticated/estado-mesas': typeof AuthenticatedEstadoMesasRoute
  '/_authenticated/mesas': typeof AuthenticatedMesasRoute
  '/_authenticated/resultados': typeof AuthenticatedResultadosRoute
  '/_authenticated/transcripcion': typeof AuthenticatedTranscripcionRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/asignaciones'
    | '/cambiar-password-temporal'
    | '/configuracion'
    | '/control-calidad'
    | '/delegados'
    | '/estado-mesas'
    | '/mesas'
    | '/resultados'
    | '/transcripcion'
    | '/users'
    | '/errors/$error'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/asignaciones'
    | '/cambiar-password-temporal'
    | '/configuracion'
    | '/control-calidad'
    | '/delegados'
    | '/estado-mesas'
    | '/mesas'
    | '/resultados'
    | '/transcripcion'
    | '/users'
    | '/'
    | '/errors/$error'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/asignaciones'
    | '/_authenticated/cambiar-password-temporal'
    | '/_authenticated/configuracion'
    | '/_authenticated/control-calidad'
    | '/_authenticated/delegados'
    | '/_authenticated/estado-mesas'
    | '/_authenticated/mesas'
    | '/_authenticated/resultados'
    | '/_authenticated/transcripcion'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transcripcion': {
      id: '/_authenticated/transcripcion'
      path: '/transcripcion'
      fullPath: '/transcripcion'
      preLoaderRoute: typeof AuthenticatedTranscripcionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resultados': {
      id: '/_authenticated/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof AuthenticatedResultadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesas': {
      id: '/_authenticated/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof AuthenticatedMesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estado-mesas': {
      id: '/_authenticated/estado-mesas'
      path: '/estado-mesas'
      fullPath: '/estado-mesas'
      preLoaderRoute: typeof AuthenticatedEstadoMesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delegados': {
      id: '/_authenticated/delegados'
      path: '/delegados'
      fullPath: '/delegados'
      preLoaderRoute: typeof AuthenticatedDelegadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control-calidad': {
      id: '/_authenticated/control-calidad'
      path: '/control-calidad'
      fullPath: '/control-calidad'
      preLoaderRoute: typeof AuthenticatedControlCalidadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cambiar-password-temporal': {
      id: '/_authenticated/cambiar-password-temporal'
      path: '/cambiar-password-temporal'
      fullPath: '/cambiar-password-temporal'
      preLoaderRoute: typeof AuthenticatedCambiarPasswordTemporalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asignaciones': {
      id: '/_authenticated/asignaciones'
      path: '/asignaciones'
      fullPath: '/asignaciones'
      preLoaderRoute: typeof AuthenticatedAsignacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAsignacionesRoute: typeof AuthenticatedAsignacionesRoute
  AuthenticatedCambiarPasswordTemporalRoute: typeof AuthenticatedCambiarPasswordTemporalRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedControlCalidadRoute: typeof AuthenticatedControlCalidadRoute
  AuthenticatedDelegadosRoute: typeof AuthenticatedDelegadosRoute
  AuthenticatedEstadoMesasRoute: typeof AuthenticatedEstadoMesasRoute
  AuthenticatedMesasRoute: typeof AuthenticatedMesasRoute
  AuthenticatedResultadosRoute: typeof AuthenticatedResultadosRoute
  AuthenticatedTranscripcionRoute: typeof AuthenticatedTranscripcionRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAsignacionesRoute: AuthenticatedAsignacionesRoute,
  AuthenticatedCambiarPasswordTemporalRoute:
    AuthenticatedCambiarPasswordTemporalRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedControlCalidadRoute: AuthenticatedControlCalidadRoute,
  AuthenticatedDelegadosRoute: AuthenticatedDelegadosRoute,
  AuthenticatedEstadoMesasRoute: AuthenticatedEstadoMesasRoute,
  AuthenticatedMesasRoute: AuthenticatedMesasRoute,
  AuthenticatedResultadosRoute: AuthenticatedResultadosRoute,
  AuthenticatedTranscripcionRoute: AuthenticatedTranscripcionRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
